#!/bin/bash 

# Below is a bash script that installs nf-test and add to your path at runtime
# usage example:
#    $  . ./nf-test-install

curl -fsSL https://code.askimed.com/install/nf-test | bash -s 0.8.1 


