name: Testing BankOperation

on:
  push: 
    branches: 
      - main

jobs:
  test:
    name: Python Helper functions
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5'   
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run Pytest
      run: |
        python -m pytest 